name: Bug Report
description: Report a bug to help us fix issues and improve the project.
title: "[Bug]: "
labels: ["🐞 BugFix"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe what is happening, including any error messages or unexpected behavior.
      placeholder: Tell us what you see!
      value: |
        - Description 1
        - Description 2
        - Description 3
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen instead.
      placeholder: Tell us what you expected!
      value: |
        - Description 1
        - Description 2
        - Description 3
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      description: Provide a step-by-step guide to reproduce the issue.
      placeholder: |
        1. In this environment...
        1. With this config...
        1. Run '...'
        1. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false

  - type: checkboxes
    id: issue-confirmation
    attributes:
      label: Issue Submission Checklist
      description: Before submitting, please confirm that the issue template is properly completed.
      options:
        - label: I have assigned this issue to myself or the appropriate person.
          required: true
        - label: I have added the appropriate labels for this issue.
          required: true
