name: 기능 요청
description: 새로운 기능, UI 개선 또는 문서 보강을 제안해 주세요.
title: "[기능]: "
labels: ["✨ 기능"]
projects: ["jhssong/7"]
body:
  - type: markdown
    attributes:
      value: |
        기능 요청을 제출해 주셔서 감사합니다!  
        제안을 더 잘 이해할 수 있도록 가능한 한 자세한 내용을 제공해 주세요.

  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 해당 기능을 자세히 설명해 주세요. 어떤 문제를 해결하며, 프로젝트에 어떻게 기여할 수 있나요?
      placeholder: 기능을 명확히 설명해 주세요.
      value: |
        - 설명 1
        - 설명 2
        - 설명 3
    validations:
      required: true

  - type: textarea
    id: todos
    attributes:
      label: 구현 단계 (TODO)
      description: 이 기능을 구현하기 위해 필요한 단계를 정리해 주세요.
      value: |
        - [ ] TODO 1
        - [ ] TODO 2
        - [ ] TODO 3
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보 및 참고 자료
      description: 이 기능 요청과 관련된 추가 정보, 링크 또는 참고 자료를 제공해 주세요.
      placeholder: 관련 토론, 문서 링크 또는 유용한 자료를 포함해 주세요.
    validations:
      required: false

  - type: checkboxes
    id: feature-confirmation
    attributes:
      label: 기능 요청 체크리스트
      description: 기능 요청 템플릿을 올바르게 작성했는지 확인해 주세요.
      options:
        - label: 이 이슈를 나 자신 또는 적절한 담당자에게 할당했습니다.
          required: true
        - label: 이 이슈에 적절한 라벨을 추가했습니다.
          required: true
