name: Feature Request
description: Suggest a new feature, UI improvement, or documentation enhancement.
title: "[Feat]: "
labels: ["✨ Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request!  
        Please provide as much detail as possible to help us understand your suggestion.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature in detail. What problem does it solve? How will it improve the project?
      placeholder: Explain the feature clearly.
      value: |
        - Description 1
        - Description 2
        - Description 3
    validations:
      required: true

  - type: textarea
    id: todos
    attributes:
      label: Implementation Steps (TODO)
      description: Outline the steps required to implement this feature.
      value: |
        - [ ] TODO 1
        - [ ] TODO 2
        - [ ] TODO 3
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context & References
      description: Provide any additional information, links, or references related to this feature request.
      placeholder: Include related discussions, documentation links, or any useful resources.
    validations:
      required: false

  - type: checkboxes
    id: feature-confirmation
    attributes:
      label: Feature Request Checklist
      description: Please confirm that you have properly filled out this feature request template.
      options:
        - label: I have assigned this issue to myself or the appropriate person.
          required: true
        - label: I have added the appropriate labels for this issue.
          required: true
